jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    strategy:
      matrix:
        java-version:
        - 11.0.3
        - 11
        os:
        - ubuntu-latest
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
